// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/slicing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceRequest) Reset() {
	*x = SliceRequest{}
	mi := &file_proto_slicing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceRequest) ProtoMessage() {}

func (x *SliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slicing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceRequest.ProtoReflect.Descriptor instead.
func (*SliceRequest) Descriptor() ([]byte, []int) {
	return file_proto_slicing_proto_rawDescGZIP(), []int{0}
}

func (x *SliceRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type SliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlicedData    []byte                 `protobuf:"bytes,1,opt,name=sliced_data,json=slicedData,proto3" json:"sliced_data,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceResponse) Reset() {
	*x = SliceResponse{}
	mi := &file_proto_slicing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceResponse) ProtoMessage() {}

func (x *SliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_slicing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceResponse.ProtoReflect.Descriptor instead.
func (*SliceResponse) Descriptor() ([]byte, []int) {
	return file_proto_slicing_proto_rawDescGZIP(), []int{1}
}

func (x *SliceResponse) GetSlicedData() []byte {
	if x != nil {
		return x.SlicedData
	}
	return nil
}

func (x *SliceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_slicing_proto protoreflect.FileDescriptor

const file_proto_slicing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/slicing.proto\x12\x06slicer\"+\n" +
	"\fSliceRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\"H\n" +
	"\rSliceResponse\x12\x1f\n" +
	"\vsliced_data\x18\x01 \x01(\fR\n" +
	"slicedData\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2B\n" +
	"\x06Slicer\x128\n" +
	"\x05Slice\x12\x14.slicer.SliceRequest\x1a\x15.slicer.SliceResponse(\x010\x01B\x12Z\x10slicer-api/protob\x06proto3"

var (
	file_proto_slicing_proto_rawDescOnce sync.Once
	file_proto_slicing_proto_rawDescData []byte
)

func file_proto_slicing_proto_rawDescGZIP() []byte {
	file_proto_slicing_proto_rawDescOnce.Do(func() {
		file_proto_slicing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_slicing_proto_rawDesc), len(file_proto_slicing_proto_rawDesc)))
	})
	return file_proto_slicing_proto_rawDescData
}

var file_proto_slicing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_slicing_proto_goTypes = []any{
	(*SliceRequest)(nil),  // 0: slicer.SliceRequest
	(*SliceResponse)(nil), // 1: slicer.SliceResponse
}
var file_proto_slicing_proto_depIdxs = []int32{
	0, // 0: slicer.Slicer.Slice:input_type -> slicer.SliceRequest
	1, // 1: slicer.Slicer.Slice:output_type -> slicer.SliceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_slicing_proto_init() }
func file_proto_slicing_proto_init() {
	if File_proto_slicing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_slicing_proto_rawDesc), len(file_proto_slicing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_slicing_proto_goTypes,
		DependencyIndexes: file_proto_slicing_proto_depIdxs,
		MessageInfos:      file_proto_slicing_proto_msgTypes,
	}.Build()
	File_proto_slicing_proto = out.File
	file_proto_slicing_proto_goTypes = nil
	file_proto_slicing_proto_depIdxs = nil
}
