// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/slicing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Slicer_Slice_FullMethodName = "/slicer.Slicer/Slice"
)

// SlicerClient is the client API for Slicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlicerClient interface {
	Slice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SliceRequest, SliceResponse], error)
}

type slicerClient struct {
	cc grpc.ClientConnInterface
}

func NewSlicerClient(cc grpc.ClientConnInterface) SlicerClient {
	return &slicerClient{cc}
}

func (c *slicerClient) Slice(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SliceRequest, SliceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Slicer_ServiceDesc.Streams[0], Slicer_Slice_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SliceRequest, SliceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Slicer_SliceClient = grpc.BidiStreamingClient[SliceRequest, SliceResponse]

// SlicerServer is the server API for Slicer service.
// All implementations must embed UnimplementedSlicerServer
// for forward compatibility.
type SlicerServer interface {
	Slice(grpc.BidiStreamingServer[SliceRequest, SliceResponse]) error
	mustEmbedUnimplementedSlicerServer()
}

// UnimplementedSlicerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlicerServer struct{}

func (UnimplementedSlicerServer) Slice(grpc.BidiStreamingServer[SliceRequest, SliceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Slice not implemented")
}
func (UnimplementedSlicerServer) mustEmbedUnimplementedSlicerServer() {}
func (UnimplementedSlicerServer) testEmbeddedByValue()                {}

// UnsafeSlicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlicerServer will
// result in compilation errors.
type UnsafeSlicerServer interface {
	mustEmbedUnimplementedSlicerServer()
}

func RegisterSlicerServer(s grpc.ServiceRegistrar, srv SlicerServer) {
	// If the following call pancis, it indicates UnimplementedSlicerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Slicer_ServiceDesc, srv)
}

func _Slicer_Slice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SlicerServer).Slice(&grpc.GenericServerStream[SliceRequest, SliceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Slicer_SliceServer = grpc.BidiStreamingServer[SliceRequest, SliceResponse]

// Slicer_ServiceDesc is the grpc.ServiceDesc for Slicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Slicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slicer.Slicer",
	HandlerType: (*SlicerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Slice",
			Handler:       _Slicer_Slice_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/slicing.proto",
}
